language: python
python:
  - "3.8"

dist: xenial

services:
  - docker

install:
  - pip install pipenv
  - ./go build

jobs:
  include:
    - stage: lint
      script: ./go lint
    - stage: test
      script: ./go test
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_IMAGE_TAG .
      - docker images
      - docker tag $DOCKER_IMAGE_TAG $DOCKER_USERNAME/$DOCKER_IMAGE_TAG
      - docker push $DOCKER_USERNAME/$DOCKER_IMAGE_TAG
